name: Argon
on: [pull_request]
jobs:
  scan:
    name: Argon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # origin: v2.3.5
      - name: Argon Security
        uses: guyb1/action@ab645a12c71b02f0d573fe6ea82bde96318e8570 # origin: v1.1
        env:
          ARGON_SCANNER: https://demo-actions.argon.io
          DEBUG: "true"
        with:
          audit-only: true
          argon-token: "${{ secrets.ARGON_TOKEN }}"
